#ifndef __UNIFIED_GRAPHIC_DISPLAY_CONFIG_H__
#define __UNIFIED_GRAPHIC_DISPLAY_CONFIG_H__

#if defined(TARGET_NAME) && (TARGET_NAME == GIGA)
//#undef GRAPHIC_DISPLAY_HAL_USE_GIGA_DISPLAY_GFX
#else
#undef GRAPHIC_DISPLAY_HAL_USE_GIGA_DISPLAY_GFX
#endif /* TARGET_NAME == GIGA */
#undef GRAPHIC_DISPLAY_HAL_USE_BODMER_TFT_ESPI
//#undef GRAPHIC_DISPLAY_HAL_USE_ADAFRUIT_GFX

#endif /* __UNIFIED_GRAPHIC_DISPLAY_CONFIG_H__ */